apiVersion: v1
kind: Service
metadata:
  name: backend-nombres-service
  labels:
    app: backend-nombres
spec:
  type: ClusterIP
  selector:
    app: backend  
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
