# Configuración del Backend
backend:
  name: backend
  serviceName: backend-nombres-service

  image:
    repository: miguelfeo/kubernetesback
    tag: "1.2"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8087

  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

# Configuración del Frontend
frontend:
  name: frontend
  serviceName: frontend-service

  image:
    repository: miguelfeo/kubernetesfront
    tag: "1.1"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

# Configuración de Ingress
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
  paths:
    - path: /
      pathType: Prefix
      serviceName: frontend-service
      servicePort: 80
    - path: /backend
      pathType: Prefix
      serviceName: backend-nombres-service
      servicePort: 8087
