#back
backName: backend
backService: backend-nombres-service



imageBack: 
  repository: miguelfeo/kubernetesback
  tag: "1.2"

#front


frontName: frontend
frontService: frontend-service

imageFront: 
  repository: miguelfeo/kubernetesfront
  tag: "1.1"

nameOverride: ""
fullnameOverride: ""




#ahorita resuelvo esto de abajo






