apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.serviceName }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
