apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backService }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.backName}}  
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
