apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontName}} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.frontName}} 
  template:
    metadata:
      labels:
        app: {{ .Values.frontName}} 
    spec:
      containers:
      - name: {{ .Values.frontName}} 
        image: {{ .Values.imageFront.repository }}:{{ .Values.imageFront.tag }}
        ports:
        - containerPort: 5173