apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.serviceName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - protocol: TCP
      port: 80        # Puerto accesible dentro del cluster
      targetPort: 5173 # Puerto real del contenedor
