apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontService}}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.frontName}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
