apiVersion: batch/v1
kind: Job
metadata:
  name: init-db-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init-db
          image: postgres:16
          command: ["psql"]
          args:
            - -h
            - postgres-service
            - -U
            - postgres
            - -d
            - nombres  
            - -c
            - |
              CREATE TABLE IF NOT EXISTS nombres (
                  id SERIAL PRIMARY KEY,
                  nombre VARCHAR(100)
              );
              
          env:
            - name: PGPASSWORD
              value: "securor"
